// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Json2CsharpClass
{

    internal class Image
    {
        //public string startdate { get; set; }
        //public string fullstartdate { get; set; }
        //public string enddate { get; set; }
        public string url { get; set; }
        //public string urlbase { get; set; }
        public string copyright { get; set; }
        //public string copyrightlink { get; set; }
        //public string title { get; set; }
        //public string quiz { get; set; }
        //public bool wp { get; set; }
        //public string hsh { get; set; }
        //public int drk { get; set; }
        //public int top { get; set; }
        //public int bot { get; set; }
        public byte[] raw { get; set; }
        public IList<object> hs { get; set; }
    }

    //internal class Tooltips
    //{
    //    //public string loading { get; set; }
    //    //public string previous { get; set; }
    //    //public string next { get; set; }
    //    //public string walle { get; set; }
    //    //public string walls { get; set; }
    //}

    internal class SampleResponse1
    {
        public IList<Image> images { get; set; }
        //public Tooltips tooltips { get; set; }
    }

}
